### ISSUE TITLE
Integration template

### ISSUE THREAD

**Issue by maidmaid** [meons/HEVS-Android-tourism#1]
Yo calag ! Can you :
- [x] update fixtures by adding some users joined to an office (username and pwd not randomized),
- [x] integrate login form of fosuser with base template and adminlte design,
- [x] clean adminlte interface by :
  - removing useless items (search bar, notifications items, ...),
  - replacing AdminLTE title by name's office that is connected,
  - replacing Alexandre Pierce title by username's user that is connected,
  - and adding logout link.

Thx amigo !

**Comment by ZHB** [comment]
Je m'essayais aux templates alors j'ai créé le template de login. 
Comme celui-ci est un template "light" par rapport aux pages internes d'AdminLTE j'ai créé 2 bases, une light et une full qui elles héritent de "layout.html.twig" pour éviter d'avoir les assets dans deux layouts séparés. 

Comment t'aurais fait Dany, parce que je me demande si c'est foireux ou pas ?

**Comment by maidmaid** [comment]
Your solution works Vinc', it's ok. But I propose easiler : 

have only one base template containing all : administration html code in content block with empty body block. For login template, this template extends base and we write login html code in content block (and not in body). All others templates must just extend base and we write html in body block. 

Little comment : all style tag must to be in stylesheets block, and style tag in javascripts block. 

PS : yes, I pratice my english.

**Comment by ZHB** [comment]
If you want to speak in english...;)

Effectively, your solution is better, I didn't think about it. 
Sure, assets needs to be in their respective blocks, I just didn't want modify Simeon's work.

I corrected layouts as you specified.

**Comment by meons** [comment]
Yo,
I just committed the changes and all points should be okay now.
Let me know if something is wrong =).

**Comment by meons** [comment]
Use the following blocks for page content.

<code>
{% block header %}
{% block header_desc %}
{% block body %}
</code>

See / route (home) for example.

**Comment by maidmaid** [comment]
:+1: calag !
