### ISSUE TITLE
Add a way to mark tourist answered quiz as treated

### ISSUE THREAD

**Issue by ZHB** [meons/HEVS-Android-tourism#12]
One last useful functionality is a way to manage treated or not tourist quiz. 

What do you think about it ?

**Comment by maidmaid** [comment]
:+1: good idea !
Just a detail : instead treaded notion, I prefer say "new tourist" with `is_new` property in tourist entity. At first rendered, we mark simply new flag to false.

**Comment by ZHB** [comment]
OK, but a tourist can have more than one quiz. We have to mark tourist as "not new" only if all tourist quizzes were read by tourist office.

**Comment by maidmaid** [comment]
Ah, I thought tourist was joined by only one quiz... In this case, maybe it is good to show a count of quizzes in the tourist list like : 

| Ref | Quiz |
| --- | --- |
| REF1 | 3 quizzes (`2 new`) |

If you agree with me, can you open a new issue about this ?

Else yes: consider that tourist is new while it exist new quizz is ok for me.

**Comment by ZHB** [comment]
I agree with you, it's the more visual and logical solution to quickly see tourist quizzes. #13

**Comment by ZHB** [comment]
Ok, we can now add this notion in the participation entity with a boolean flag "isNew"

**Comment by maidmaid** [comment]
:+1:

**Comment by maidmaid** [comment]
We have to show label `is new`.
