### ISSUE TITLE
Add a notion of Gender and Age

### ISSUE THREAD

**Issue by ZHB** [meons/HEVS-Android-tourism#15]
A tourist has to indicate his Gender and age when he answer a quiz. 

I think it will be better to keep those notions separate from quizzes and force a tourist to complete those fields when he is created.

**Comment by maidmaid** [comment]
@ZHB, about #28, you can add my work by adding this line in new tab named Tourist :

``` twig
{{ include('tourist/show.html.twig', { tourist: participation.tourist }) }}
```
