### ISSUE TITLE
Add id in table between tourist and quiz

### ISSUE THREAD

**Issue by maidmaid** [meons/HEVS-Android-tourism#18]
Azure want an id for each table and primary key of `tourist_quiz` table is a composite key, and azure doesn't like it. We must add an id field.

Please to work in branch named `participation` for this issue.

**Comment by maidmaid** [comment]
Info : `AppBundle\Entity\Participation` will be the table between tourist and quiz entities.

**Comment by meons** [comment]
From now I ll use this branch in Azure web site deployment.

**Comment by maidmaid** [comment]
@ZHB can you update `doc/model/model.png` by adding participation entity please ?

**Comment by ZHB** [comment]
I just opened a new issue about your request : #23
