### ISSUE TITLE
Follow PSR 2 code style

### ISSUE THREAD

**Issue by maidmaid** [meons/HEVS-Android-tourism#2]
Hey my friends, do not forget to follow PSR 2 code style else Voldemort will kill you :zap:
- [PSR 2](http://www.php-fig.org/psr/psr-2/)
- [Configuration in PhpStorm](https://confluence.jetbrains.com/display/PhpStorm/Getting+Started+-+Symfony+Development+using+PhpStorm#GettingStarted-SymfonyDevelopmentusingPhpStorm-Symfony2CodeStyle)

**Comment by ZHB** [comment]
I will read this coding style guide this morning, while I'm at Malera.com :wink:

**Comment by meons** [comment]
=)
