### ISSUE TITLE
Update model in doc folder

### ISSUE THREAD

**Issue by ZHB** [meons/HEVS-Android-tourism#23]
Here is the updated model representing our entities after that participation branch will be merged. 

Notice that I'm not sure about relations direction, and for example between "Question" and "Category" I have to add one or two relations ?

![classdiagram](https://cloud.githubusercontent.com/assets/219280/9602116/3ecfba5e-50a6-11e5-8d68-b8c66af49db3.png)

**Comment by ZHB** [comment]
Wrong relationship between Result and Quiz. See : #24

**Comment by maidmaid** [comment]
Between Question and Category, there is one relation, and Question is the owning side. I don't know how draw this with uml, sorry...

**Comment by ZHB** [comment]
Ok. I corrected the diagram.

![classdiagram2](https://cloud.githubusercontent.com/assets/219280/9625556/5411b9e2-5157-11e5-95b5-a50a110b95d8.png)

**Comment by maidmaid** [comment]
We have to add this model in doc folder.
