### ISSUE TITLE
Wrong relationship between Result and Quiz

### ISSUE THREAD

**Issue by ZHB** [meons/HEVS-Android-tourism#24]
We have to delete relation between Quiz and Result to replace it with a relation between Quiz and Participation.

With the actual relationship, we can't have results for only one answered quiz, so we must restrict the user to answer only one time a quiz.

With the new solution, a user can answer quizzes unlimited times.

**Comment by maidmaid** [comment]
Can answer quizzes unlimited times won't be used here, but you are right, join quiz with participation is more clear.
