### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by maidmaid** [meons/HEVS-Android-tourism#3]
- http://symfony.com/doc/current/book/translation.html
- http://symfony.com/doc/current/best_practices/i18n.html

**Comment by meons** [comment]
http://symfony.com/doc/current/cookbook/session/locale_sticky_session.html

So if I understood correctly the symfony doc about translation, the link above explain exactly what we need, namely change language for entire session by clicking on a link. Right ?

**Comment by ZHB** [comment]
I think i18n is configured correctly. We have to add translations in xlf files and Twig templates now.

**Comment by maidmaid** [comment]
It misses some translations.
