### ISSUE TITLE
Add breadcrumb

### ISSUE THREAD

**Issue by maidmaid** [meons/HEVS-Android-tourism#6]
Homepage
- `Home` : homepage

Quiz
- `Home > Quiz` : Quiz index
- `Home > Quiz > Quiz 123` : Show / Edit Quiz

Tourist
- `Home > Tourist` : Tourist index
- `Home > Tourist > #REF123` : Show result

AdminLTE has breadcrumb component.

**Comment by meons** [comment]
I added default breadcrumb from adminLte to the base.html.twig page.

``` html
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
    <li class="active">Here</li>
</ol>
```

Now we have to find a dynamic and clean way to update that for each page load.

**Comment by ZHB** [comment]
Maybe for the breadcrumb : https://github.com/whiteoctober/BreadcrumbsBundle

**Comment by maidmaid** [comment]
Is it really necessary to manage dynamically the breadcrumb ? We have not a lot of pages at least, juste 5... I propose instead to do simplier by hardcoding breadcrumb in template. Are you ok ?

**Comment by meons** [comment]
Yeah you're right @maidmaid, I'll add a breadcrumb block in base template.

**Comment by meons** [comment]
Done! Look at default/index or quiz/index view for an example.

**Comment by ZHB** [comment]
:+1:  Maybe you can remove <a href="">...</a>  from last breadcrumb node, because we are already on the current page. Generally last element is inactive.
